providers:
  docker:
    exposedByDefault: false
  file:
    watch: true
    filename: /etc/traefik/dynamic.yml

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true

accessLog: {}

api:
  dashboard: false
