# Generated by Django 4.2.30 on 2026-06-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dies.die')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['die', 'timestamp'], name='history_die_die_id_747122_idx')],
            },
        ),
    ]
