# Generated by Django 4.2.30 on 2026-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinehistory',
            name='entity_type',
            field=models.CharField(choices=[('MACHINE', 'Machine'), ('SET', 'Set'), ('CATEGORY', 'Category'), ('RACK', 'Rack')], max_length=10),
        ),
    ]
