# Generated by Django 4.2.30 on 2026-07-10 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diehistory',
            name='die',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dies.die'),
        ),
        migrations.AddIndex(
            model_name='machinehistory',
            index=models.Index(fields=['entity_type', 'entity_id'], name='history_mac_entity__30e22d_idx'),
        ),
        migrations.AddIndex(
            model_name='machinehistory',
            index=models.Index(fields=['timestamp'], name='history_mac_timesta_72b743_idx'),
        ),
        migrations.AddIndex(
            model_name='diehistory',
            index=models.Index(fields=['die', 'timestamp'], name='history_die_die_id_747122_idx'),
        ),
        migrations.AddIndex(
            model_name='diehistory',
            index=models.Index(fields=['timestamp'], name='history_die_timesta_55e75c_idx'),
        ),
    ]
