# Generated by Django 4.2.30 on 2026-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diehistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
