# Generated by Django 4.2.21 on 2026-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_machinehistory_entity_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diehistory',
            index=models.Index(fields=['die', 'field_name', 'timestamp'], name='history_die_die_id_64fa37_idx'),
        ),
    ]
