# Generated by Django 4.2.30 on 2026-06-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_diehistory_ip_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diehistory',
            index=models.Index(fields=['timestamp'], name='history_die_timesta_55e75c_idx'),
        ),
    ]
