# Generated by Django 4.2.30 on 2026-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_diehistory_history_die_die_id_64fa37_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='diehistory',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='diehistory',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
