# Generated by Django 4.2.30 on 2026-10-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0004_diehistory_hash_diehistory_prev_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, default='WIRE_DRAWING_TDS', max_length=50)),
                ('doc_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('work_order', models.CharField(db_index=True, max_length=100)),
                ('machine_name', models.CharField(blank=True, max_length=100)),
                ('material_profile', models.CharField(blank=True, default='Standard Wire Drawing', max_length=100)),
                ('quality_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('inlet_size', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('finish_size', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_passes', models.PositiveSmallIntegerField(default=0)),
                ('overall_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_elongation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dies', models.JSONField(blank=True, default=list)),
                ('passes_data', models.JSONField(blank=True, default=list)),
                ('username', models.CharField(max_length=150)),
                ('user_role', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doc_type', 'created_at'], name='history_pri_doc_typ_ff983f_idx'), models.Index(fields=['work_order', 'created_at'], name='history_pri_work_or_043329_idx')],
            },
        ),
    ]
