# Generated by Django 4.2.30 on 2026-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='set',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
