# Generated by Django 4.2.30 on 2026-06-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_id', models.CharField(max_length=50, unique=True)),
                ('die_type', models.CharField(choices=[('ROUND', 'Round'), ('FLAT', 'Flat')], max_length=10)),
                ('casing', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('CLEANING', 'Cleaning'), ('POLISHING', 'Polishing'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('MISSING', 'Missing')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.set')),
            ],
        ),
        migrations.CreateModel(
            name='RoundDie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_size', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_size', models.DecimalField(decimal_places=3, max_digits=7)),
                ('die', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rounddie', to='dies.die')),
            ],
            options={
                'indexes': [models.Index(fields=['current_size'], name='dies_roundd_current_33f836_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlatDie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('original_thickness', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_thickness', models.DecimalField(decimal_places=3, max_digits=7)),
                ('radius', models.DecimalField(decimal_places=3, max_digits=7)),
                ('die', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flatdie', to='dies.die')),
            ],
            options={
                'indexes': [models.Index(fields=['current_width', 'current_thickness'], name='dies_flatdi_current_97e58b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['status'], name='dies_die_status_ee1f73_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['casing'], name='dies_die_casing_63f282_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['die_type'], name='dies_die_die_typ_0c1a97_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['location'], name='dies_die_locatio_b37036_idx'),
        ),
    ]
