# Generated by Django 4.2.30 on 2026-07-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_id', models.CharField(max_length=50, unique=True)),
                ('die_type', models.CharField(choices=[('ROUND', 'Round'), ('FLAT', 'Flat')], max_length=10)),
                ('casing', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('CLEANING', 'Cleaning'), ('POLISHING', 'Polishing'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('MISSING', 'Missing'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('shelf', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlatDie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('punched_thickness', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_thickness', models.DecimalField(decimal_places=3, max_digits=7)),
                ('radius', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_count', models.IntegerField()),
                ('updated_count', models.IntegerField()),
                ('skipped_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('errors_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('RECUT', 'Recut / Re-bore'), ('CLEANING', 'Cleaning'), ('POLISHING', 'Polishing'), ('MEASUREMENT', 'Measurement'), ('OTHER', 'Other')], max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundDie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_size', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_size', models.DecimalField(decimal_places=3, max_digits=7)),
                ('die', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rounddie', to='dies.die')),
            ],
        ),
    ]
