# Generated by Django 4.2.30 on 2026-07-10 17:04

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dies', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='maintenancelog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='die',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='dies.die'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flatdie',
            name='die',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flatdie', to='dies.die'),
        ),
        migrations.AddField(
            model_name='die',
            name='current_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.set'),
        ),
        migrations.AddField(
            model_name='die',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.rack'),
        ),
        migrations.AddIndex(
            model_name='rounddie',
            index=models.Index(fields=['current_size'], name='dies_roundd_current_33f836_idx'),
        ),
        migrations.AddIndex(
            model_name='flatdie',
            index=models.Index(fields=['current_width', 'current_thickness'], name='dies_flatdi_current_97e58b_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['status'], name='dies_die_status_ee1f73_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['die_type'], name='dies_die_die_typ_0c1a97_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='die_location_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='die',
            index=django.contrib.postgres.indexes.GinIndex(fields=['casing'], name='die_casing_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
