# Generated by Django 4.2.30 on 2026-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('CLEANING', 'Cleaning'), ('POLISHING', 'Polishing'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('MISSING', 'Missing'), ('MAINTENANCE', 'Maintenance'), ('SCRAP', 'Scrap')], default='AVAILABLE', max_length=20),
        ),
    ]
