# Generated by Django 4.2.30 on 2026-07-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_type', models.CharField(choices=[('ROUND', 'Round'), ('FLAT', 'Flat')], max_length=10, unique=True)),
                ('max_wear_mm', models.DecimalField(decimal_places=3, default=0.05, max_digits=5)),
                ('warning_percentage', models.IntegerField(default=70)),
                ('critical_percentage', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='WearAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=15)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_alerts', to='dies.die')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
