# Generated by Django 4.2.30 on 2026-07-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0002_dietolerance_wearalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='die',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
