# Generated by Django 4.2.30 on 2026-06-20 15:51

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0002_alter_die_status'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name='die',
            name='dies_die_casing_63f282_idx',
        ),
        migrations.RemoveIndex(
            model_name='die',
            name='dies_die_locatio_b37036_idx',
        ),
        migrations.AddIndex(
            model_name='die',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='die_location_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='die',
            index=django.contrib.postgres.indexes.GinIndex(fields=['casing'], name='die_casing_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
