# Generated by Django 4.2.30 on 2026-06-27 18:29

from django.db import migrations, models


def migrate_scrap_to_scrapped(apps, schema_editor):
    Die = apps.get_model('dies', 'Die')
    Die.objects.filter(status='SCRAP').update(status='SCRAPPED')


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0003_remove_die_dies_die_casing_63f282_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_scrap_to_scrapped, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='die',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('CLEANING', 'Cleaning'), ('POLISHING', 'Polishing'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('MISSING', 'Missing'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
    ]
