# Generated by Django 4.2.30 on 2026-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0004_outboxtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxtask',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
