# Generated by Django 4.2.30 on 2026-06-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_rack'),
        ('dies', '0004_alter_die_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='die',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.rack'),
        ),
        migrations.AddField(
            model_name='die',
            name='shelf',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
