# Generated by Django 4.2.30 on 2026-07-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0005_outboxtask_payload_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='die',
            old_name='shelf',
            new_name='shelf_number',
        ),
    ]
