# Generated by Django 4.2.30 on 2026-06-27 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dies', '0006_migrate_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_count', models.IntegerField()),
                ('updated_count', models.IntegerField()),
                ('skipped_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('errors_json', models.JSONField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
    ]
