# Generated by Django 4.2.30 on 2026-07-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0007_importlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatdie',
            old_name='original_thickness',
            new_name='punched_thickness',
        ),
        migrations.RenameField(
            model_name='flatdie',
            old_name='original_width',
            new_name='punched_width',
        ),
        migrations.RenameField(
            model_name='rounddie',
            old_name='original_size',
            new_name='punched_size',
        ),
    ]
