# Generated by Django 4.2.30 on 2026-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0007_alter_flatdie_current_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='die',
            name='predicted_remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
