# Generated by Django 4.2.30 on 2026-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0010_remove_die_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['die_type', 'status'], name='dies_die_die_typ_caf6ea_idx'),
        ),
    ]
