# Generated by Django 4.2.30 on 2026-08-10 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dies', '0011_die_dies_die_die_typ_caf6ea_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnamelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DieInventoryRecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recount_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enamel_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recounts', to='dies.enamelmachine')),
            ],
            options={
                'ordering': ['-recount_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineDieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_size', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enamel_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_stocks', to='dies.enamelmachine')),
            ],
            options={
                'ordering': ['enamel_machine', 'die_size'],
                'unique_together': {('enamel_machine', 'die_size')},
            },
        ),
        migrations.CreateModel(
            name='DieInventoryRecountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_size', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('quantity', models.PositiveIntegerField()),
                ('recount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dies.dieinventoryrecount')),
            ],
            options={
                'ordering': ['die_size'],
                'unique_together': {('recount', 'die_size')},
            },
        ),
    ]
