# Generated by Django 4.2.30 on 2026-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0012_enamelmachine_dieinventoryrecount_machinediestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinventoryrecountitem',
            name='previous_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
