# Generated by Django on 2026-08-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0013_dieinventoryrecountitem_previous_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='die',
            name='predicted_remaining_days',
        ),
    ]
