# Generated by Django 4.2.30 on 2026-09-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0014_remove_die_predicted_remaining_days'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['status', 'die_type'], name='die_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='die',
            index=models.Index(fields=['rack', 'shelf_number'], name='die_rack_shelf_idx'),
        ),
    ]
