# Generated by Django 4.2.30 on 2026-09-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dies', '0015_add_composite_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='die',
            options={'ordering': ['die_id']},
        ),
        migrations.AlterModelOptions(
            name='dietolerance',
            options={'ordering': ['die_type']},
        ),
    ]
