DIE_TYPES = (
    'ROUND',
    'FLAT',
)

DIE_TYPE_CHOICES = (
    ('ROUND', 'Round'),
    ('FLAT', 'Flat'),
)

DIE_STATUSES = (
    'AVAILABLE',
    'RUNNING',
    'CLEANING',
    'POLISHING',
    'DAMAGED',
    'SCRAPPED',
    'MISSING',
    'MAINTENANCE',
)

DIE_STATUS_CHOICES = (
    ('AVAILABLE', 'Available'),
    ('RUNNING', 'Running'),
    ('CLEANING', 'Cleaning'),
    ('POLISHING', 'Polishing'),
    ('DAMAGED', 'Damaged'),
    ('SCRAPPED', 'Scrapped'),
    ('MISSING', 'Missing'),
    ('MAINTENANCE', 'Maintenance'),
)

DIE_ACTIVE_STATUSES = (
    'AVAILABLE',
    'RUNNING',
    'CLEANING',
    'POLISHING',
)

DIE_WORKFLOW_EVENT_TYPES = (
    'die_update',
    'set_update',
    'machine_update',
    'backup_update',
)

DIE_UPDATE_EVENT = DIE_WORKFLOW_EVENT_TYPES[0]
SET_UPDATE_EVENT = DIE_WORKFLOW_EVENT_TYPES[1]
MACHINE_UPDATE_EVENT = DIE_WORKFLOW_EVENT_TYPES[2]
BACKUP_UPDATE_EVENT = DIE_WORKFLOW_EVENT_TYPES[3]

DIE_WORKFLOW_ACTIONS = (
    'save',
    'delete',
    'bulk_import',
    'backup',
    'restore',
    'upload',
)

DIE_SAVE_ACTION = DIE_WORKFLOW_ACTIONS[0]
DIE_DELETE_ACTION = DIE_WORKFLOW_ACTIONS[1]
DIE_BULK_IMPORT_ACTION = DIE_WORKFLOW_ACTIONS[2]
BACKUP_CREATE_ACTION = DIE_WORKFLOW_ACTIONS[3]
BACKUP_RESTORE_ACTION = DIE_WORKFLOW_ACTIONS[4]
BACKUP_UPLOAD_ACTION = DIE_WORKFLOW_ACTIONS[5]
BACKUP_DELETE_ACTION = 'delete'

SET_SAVE_ACTION = DIE_SAVE_ACTION
SET_DELETE_ACTION = DIE_DELETE_ACTION
MACHINE_SAVE_ACTION = DIE_SAVE_ACTION
MACHINE_DELETE_ACTION = DIE_DELETE_ACTION
