# Generated by Django 4.2.30 on 2026-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized_for_tools',
            field=models.BooleanField(default=False),
        ),
    ]
