# Generated by Django 4.2.30 on 2026-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROOT', 'Root'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10),
        ),
    ]
