# Generated by Django 4.2.30 on 2026-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_authorized_for_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
