# Generated by Django 4.2.30 on 2026-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['timestamp'], name='users_usera_timesta_aabea0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['username'], name='users_usera_usernam_ecdfa9_idx'),
        ),
    ]
